# Package basics informations 
[package]
name = "avalon"
version = "0.1.0"
authors = ["Gabibou38"]

# Optional compilation param
[features]
# default = ["board_avalon_g474_rev_b"]
default = ["x86_x64_debug_target"]

# Define every board compatible with the project
board_avalon_g474_rev_a = [
    "mcu_stm32g474",
    "sensor_bmp390",
]

board_avalon_g474_rev_b = [
    "mcu_stm32g474",
    "sensor_bmp390",
]

# Define every mcu compatible with the project
mcu_stm32g474 = [
    "dep:stm32g4",
]

# Define every sensor compatible with the project
sensor_bmp390 = [
    "dep:bmp390"
]

# Define if run in debug mode
# If enabled sensors value will be emulated and all logs outputs
x86_x64_debug_target = []


# Dependencies list
[dependencies]
bmp390 = {version = "0.4.3", optional = true}
stm32g4 = { version = ">=0.16.0", features = ["stm32g474"], optional = true }

# Embedded target 
[build]
target = "thumbv7em-none-eabihf"


