/** 
* 
* @file ui_register.h
* @date 27/04/2026
* @version  1.0.0
* @note  File use to define all register included in REVISION_STATUS
*/
#ifndef INC_UI_REG_REVISION_STATUS_H_
#define INC_UI_REG_REVISION_STATUS_H_

#include "ui.h"

/*----- REVISION_STATUS registers -----*/
#define UI_REVISION_STATUS_BASE_ADDR 0x00000000
#define UI_REVISION_STATUS_ACCESS_CONTROL READ_ONLY
#define UI_REVISION_STATUS_FW_REVISION_MAJOR 0x1
#define UI_REVISION_STATUS_FW_REVISION_MINOR 0x0
#define UI_REVISION_STATUS_FW_REVISION_FIX 0x0
#define UI_REVISION_STATUS_UI_REVISION_MAJOR 0x1
#define UI_REVISION_STATUS_UI_REVISION_MINOR 0x0
#define UI_REVISION_STATUS_UI_REVISION_FIX 0x0

/* ----- SYSTEM_STATUS registers -----*/
#define UI_SYSTEM_STATUS_BASE_ADDR 0x00000020
#define UI_SYSTEM_STATUS_ACCESS_CONTROL READ_ONLY  
#define UI_SYSTEM_STATUS_SYSTEM_FSM_DEFAULT_VALUE 0x0  

/* ----- PID_CONTROL registers -----*/
#define UI_PID_CONTROL_BASE_ADDR 0x00000040
#define UI_PID_CONTROL_ACCESS_CONTROL READ_WRITE   

/* ----- COMMAND registers -----*/
#define UI_COMMAND_BASE_ADDR 0x00000080
#define UI_COMMAND_ACCESS_CONTROL READ_WRITE   

/* ----- SENSOR_CONFIG registers -----*/
#define UI_SENSOR_CONFIG_BASE_ADDR 0x000000E4
#define UI_SENSOR_CONFIG_ACCESS_CONTROL READ_WRITE  

/* ----- DEBUG registers -----*/
#define UI_DEBUG_BASE_ADDR 0x00000148
#define UI_DEBUG_ACCESS_CONTROL READ_ONLY  

/* ----- ACTUATOR_CONFIG registers -----*/
#define UI_ACTUATOR_CFG_BASE_ADDR 0x000001AC
#define UI_ACTUATOR_CFG_ACCESS_CONTROL READ_ONLY  

/* ----- FLIGHT_CONTROL registers -----*/
#define UI_FLIGHT_CTRL_BASE_ADDR 0x00000210
#define UI_FLIGHT_CTRL_ACCESS_CONTROL WRITE_ONLY  

/* ----- ALERTS registers -----*/
#define UI_ALERTS_BASE_ADDR 0x00000274
#define UI_ALERTS_ACCESS_CONTROL READ_ONLY  

/* ----- MEMORY_CONTROL registers -----*/
#define UI_MEMORY_CTRL_BASE_ADDR 0x000002D8
#define UI_MEMORY_CTRL_ACCESS_CONTROL READ_WRITE  


#endif